//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int duration { get; set; }
        public int parkid { get; set; }
        public string plateno { get; set; }
        public double price { get; set; }
        public int cid { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Parking Parking { get; set; }
        public virtual User User { get; set; }
    }
}
